- name: jinja file template edit
  hosts: localhost

  vars:
      file_name: study.conf
      path: 
        - /var/www/html/
      mail:
        - abhishek1997sh@gmail.com
      server_name:
        - test.byteportfolio.in


  tasks:
        - name: template
          template:
              src: file.j2
              dest: "{{file_name}}"

        - name: get container id 
          command: "sh con_id.sh"
          #args:
          #  executable: /bin/bash

        - name: container_id
          command: "cat ../tmp_data.txt"
          register: con_id

        - name: content show
          debug:
                msg: "{{con_id.stdout}}"
                
        - name: copy content data in container
          community.docker.docker_container_copy_into:
              container: "{{con_id.stdout}}"
              path: "{{file_name}}"
              container_path: /etc/apache2/sites-available/000-default.conf
          
        - name: container stop
          community.docker.docker_container:
             name: "{{con_id.stdout}}"
             state: stopped

        - name: container start
          community.docker.docker_container:
             name: "{{con_id.stdout}}"
             state: started
          
