- name: jinja file template edit
  hosts: localhost

  vars:
      file_name: study.conf
      path: 
        - /var/www/html/
      mail:
        - abhishek1997sh@gmail.com
      server_name:
        - test.byteportfolio.in


  tasks:
        - name: template
          template:
              src: file.j2
              dest: "{{file_name}}"

        - name: container_id
          command: cat < ../tmp_data.txt
          register: con_id
        
        - name: copy content data in container
          community.docker.docker_container_copy_into:
              container: "{{con_id}}"
              path: "{{file_name}}"
              container_path: /etc/apache2/sites-available/000-default.conf
          
        - name: container reboot
          command: docker restart "{{con_id}}"
